-- Add missing columns to catalog table
ALTER TABLE public.catalog
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS important_info TEXT,
ADD COLUMN IF NOT EXISTS images TEXT[],
ADD COLUMN IF NOT EXISTS weight DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS length DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS width DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS height DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_weekday BOOLEAN DEFAULT true;
